name: Download y2b video and upload to musetransfer

on:
  workflow_dispatch:
    inputs:
      url:
        description: "请输入youtube视频地址："
        required: true
      res:
        description: "优先分辨率："
        required: true
        default: "1080p"
        type: choice
        options:
          - 1080p
          - 720p
          - 480p
          - 360p

env:
  TOOLS_PATH: /usr/local/bin/tools
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: tools cache
        id: tools-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.TOOLS_PATH }}
          key: ${{ runner.os }}-tools-${{ hashFiles('scripts/install.sh') }}
          restore-keys: |
            ${{ runner.os }}-tools-

      - name: Install dependency
        run: |
          bash scripts/install.sh
        env:
          TOOLS_CACHE_HIT: ${{ steps.tools-cache.outputs.cache-hit }}
      
      - name: Run
        run: |
          python ./scripts/run.py "${URL}" "${RES}"
        env:
          URL: ${{ github.event.inputs.url }}
          RES: ${{ github.event.inputs.res }}
